import './menu.css';

import CloseIcon from '@mui/icons-material/Close';

function MenuImage() {
    return (
            <div className="menu">
                <div className="menu--top-bar">
                    <div>Select image</div>
                    <i><CloseIcon /></i>
                </div>
                <div className="menu--item-selector">
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                    <div className="menu--item-select"></div>
                </div>
            </div>
    );
}

export default MenuImage;
