import { ReactComponent as I1 } from '../../assets/svg/1.svg';
import { ReactComponent as I2 } from '../../assets/svg/2.svg';
import { ReactComponent as I3 } from '../../assets/svg/3.svg';
import { ReactComponent as I4 } from '../../assets/svg/4.svg';
import { ReactComponent as I5 } from '../../assets/svg/5.svg';
import { ReactComponent as I6 } from '../../assets/svg/6.svg';
import { ReactComponent as I7 } from '../../assets/svg/7.svg';
import { ReactComponent as I8 } from '../../assets/svg/8.svg';
import { ReactComponent as I9 } from '../../assets/svg/9.svg';
import { ReactComponent as I10 } from '../../assets/svg/10.svg';
import { ReactComponent as I11 } from '../../assets/svg/11.svg';
import { ReactComponent as I12 } from '../../assets/svg/12.svg';
import { ReactComponent as I13 } from '../../assets/svg/13.svg';
import { ReactComponent as I14 } from '../../assets/svg/14.svg';
import { ReactComponent as I15 } from '../../assets/svg/15.svg';
import { ReactComponent as I16 } from '../../assets/svg/16.svg';
import { ReactComponent as I17 } from '../../assets/svg/17.svg';
import { ReactComponent as I18 } from '../../assets/svg/18.svg';
import { ReactComponent as I19 } from '../../assets/svg/19.svg';
import { ReactComponent as I20 } from '../../assets/svg/20.svg';
import { ReactComponent as I21 } from '../../assets/svg/21.svg';
import { ReactComponent as I22 } from '../../assets/svg/22.svg';
import { ReactComponent as I23 } from '../../assets/svg/23.svg';
import { ReactComponent as I24 } from '../../assets/svg/24.svg';
import { ReactComponent as I25 } from '../../assets/svg/25.svg';
import { ReactComponent as I26 } from '../../assets/svg/26.svg';
import { ReactComponent as I27 } from '../../assets/svg/27.svg';
import { ReactComponent as I28 } from '../../assets/svg/28.svg';
import { ReactComponent as I29 } from '../../assets/svg/29.svg';
import { ReactComponent as I30 } from '../../assets/svg/30.svg';
import { ReactComponent as I31 } from '../../assets/svg/31.svg';
import { ReactComponent as I32 } from '../../assets/svg/32.svg';
import { ReactComponent as I33 } from '../../assets/svg/33.svg';
import { ReactComponent as I34 } from '../../assets/svg/34.svg';
import { ReactComponent as I35 } from '../../assets/svg/35.svg';
import { ReactComponent as I36 } from '../../assets/svg/36.svg';
import { ReactComponent as I37 } from '../../assets/svg/37.svg';
import { ReactComponent as I38 } from '../../assets/svg/38.svg';
import { ReactComponent as I39 } from '../../assets/svg/39.svg';
import { ReactComponent as I40 } from '../../assets/svg/40.svg';
import { ReactComponent as I41 } from '../../assets/svg/41.svg';
import { ReactComponent as I42 } from '../../assets/svg/42.svg';
import { ReactComponent as I43 } from '../../assets/svg/43.svg';
import { ReactComponent as I44 } from '../../assets/svg/44.svg';
import { ReactComponent as I45 } from '../../assets/svg/45.svg';
import { ReactComponent as I46 } from '../../assets/svg/46.svg';
import { ReactComponent as I47 } from '../../assets/svg/47.svg';
import { ReactComponent as I48 } from '../../assets/svg/48.svg';
import { ReactComponent as I49 } from '../../assets/svg/49.svg';
import { ReactComponent as I50 } from '../../assets/svg/50.svg';
import { ReactComponent as I51 } from '../../assets/svg/51.svg';
import { ReactComponent as I52 } from '../../assets/svg/52.svg';
import { ReactComponent as I53 } from '../../assets/svg/53.svg';
import { ReactComponent as I54 } from '../../assets/svg/54.svg';
import { ReactComponent as I55 } from '../../assets/svg/55.svg';
import { ReactComponent as I56 } from '../../assets/svg/56.svg';
import { ReactComponent as I57 } from '../../assets/svg/57.svg';
import { ReactComponent as I58 } from '../../assets/svg/58.svg';
import { ReactComponent as I59 } from '../../assets/svg/59.svg';
import { ReactComponent as I60 } from '../../assets/svg/60.svg';
import { ReactComponent as I61 } from '../../assets/svg/61.svg';
import { ReactComponent as I62 } from '../../assets/svg/62.svg';
import { ReactComponent as I63 } from '../../assets/svg/63.svg';
import { ReactComponent as I64 } from '../../assets/svg/64.svg';
import { ReactComponent as I65 } from '../../assets/svg/65.svg';
import { ReactComponent as I66 } from '../../assets/svg/66.svg';
import { ReactComponent as I67 } from '../../assets/svg/67.svg';
import { ReactComponent as I68 } from '../../assets/svg/68.svg';
import { ReactComponent as I69 } from '../../assets/svg/69.svg';
import { ReactComponent as I70 } from '../../assets/svg/70.svg';
import { ReactComponent as I71 } from '../../assets/svg/71.svg';
import { ReactComponent as I72 } from '../../assets/svg/72.svg';
import { ReactComponent as I73 } from '../../assets/svg/73.svg';
import { ReactComponent as I74 } from '../../assets/svg/74.svg';
import { ReactComponent as I75 } from '../../assets/svg/75.svg';
import { ReactComponent as I76 } from '../../assets/svg/76.svg';
import { ReactComponent as I77 } from '../../assets/svg/77.svg';
import { ReactComponent as I78 } from '../../assets/svg/78.svg';
import { ReactComponent as I79 } from '../../assets/svg/79.svg';
import { ReactComponent as I80 } from '../../assets/svg/80.svg';
import { ReactComponent as I81 } from '../../assets/svg/81.svg';
import { ReactComponent as I82 } from '../../assets/svg/82.svg';
import { ReactComponent as I83 } from '../../assets/svg/83.svg';
import { ReactComponent as I84 } from '../../assets/svg/84.svg';
import { ReactComponent as I85 } from '../../assets/svg/85.svg';
import { ReactComponent as I86 } from '../../assets/svg/86.svg';
import { ReactComponent as I87 } from '../../assets/svg/87.svg';
import { ReactComponent as I88 } from '../../assets/svg/88.svg';
import { ReactComponent as I89 } from '../../assets/svg/89.svg';
import { ReactComponent as I90 } from '../../assets/svg/90.svg';
import { ReactComponent as I91 } from '../../assets/svg/91.svg';
import { ReactComponent as I92 } from '../../assets/svg/92.svg';
import { ReactComponent as I93 } from '../../assets/svg/93.svg';
import { ReactComponent as I94 } from '../../assets/svg/94.svg';
import { ReactComponent as I95 } from '../../assets/svg/95.svg';
import { ReactComponent as I96 } from '../../assets/svg/96.svg';
import { ReactComponent as I97 } from '../../assets/svg/97.svg';
import { ReactComponent as I98 } from '../../assets/svg/98.svg';
import { ReactComponent as I99 } from '../../assets/svg/99.svg';
import { ReactComponent as I100 } from '../../assets/svg/100.svg';
import { ReactComponent as I101 } from '../../assets/svg/101.svg';
import { ReactComponent as I102 } from '../../assets/svg/102.svg';
import { ReactComponent as I103 } from '../../assets/svg/103.svg';
import { ReactComponent as I104 } from '../../assets/svg/104.svg';
import { ReactComponent as I105 } from '../../assets/svg/105.svg';
import { ReactComponent as I106 } from '../../assets/svg/106.svg';
import { ReactComponent as I107 } from '../../assets/svg/107.svg';
import { ReactComponent as I108 } from '../../assets/svg/108.svg';
import { ReactComponent as I109 } from '../../assets/svg/109.svg';
import { ReactComponent as I110 } from '../../assets/svg/110.svg';
import { ReactComponent as I111 } from '../../assets/svg/111.svg';
import { ReactComponent as I112 } from '../../assets/svg/112.svg';
import { ReactComponent as I113 } from '../../assets/svg/113.svg';
import { ReactComponent as I114 } from '../../assets/svg/114.svg';
import { ReactComponent as I115 } from '../../assets/svg/115.svg';
import { ReactComponent as I116 } from '../../assets/svg/116.svg';
import { ReactComponent as I117 } from '../../assets/svg/117.svg';
import { ReactComponent as I118 } from '../../assets/svg/118.svg';
import { ReactComponent as I119 } from '../../assets/svg/119.svg';
import { ReactComponent as I120 } from '../../assets/svg/120.svg';
import { ReactComponent as I121 } from '../../assets/svg/121.svg';
import { ReactComponent as I122 } from '../../assets/svg/122.svg';
import { ReactComponent as I123 } from '../../assets/svg/123.svg';
import { ReactComponent as I124 } from '../../assets/svg/124.svg';
import { ReactComponent as I125 } from '../../assets/svg/125.svg';
import { ReactComponent as I126 } from '../../assets/svg/126.svg';
import { ReactComponent as I127 } from '../../assets/svg/127.svg';
import { ReactComponent as I128 } from '../../assets/svg/128.svg';
import { ReactComponent as I129 } from '../../assets/svg/129.svg';
import { ReactComponent as I130 } from '../../assets/svg/130.svg';
import { ReactComponent as I131 } from '../../assets/svg/131.svg';
import { ReactComponent as I132 } from '../../assets/svg/132.svg';
import { ReactComponent as I133 } from '../../assets/svg/133.svg';
import { ReactComponent as I134 } from '../../assets/svg/134.svg';
import { ReactComponent as I135 } from '../../assets/svg/135.svg';
// import { ReactComponent as I136 } from '../../assets/svg/136.svg';
// import { ReactComponent as I137 } from '../../assets/svg/137.svg';
// import { ReactComponent as I138 } from '../../assets/svg/138.svg';
// import { ReactComponent as I139 } from '../../assets/svg/139.svg';
// import { ReactComponent as I140 } from '../../assets/svg/140.svg';
// import { ReactComponent as I141 } from '../../assets/svg/141.svg';
// import { ReactComponent as I142 } from '../../assets/svg/142.svg';
// import { ReactComponent as I143 } from '../../assets/svg/143.svg';
// import { ReactComponent as I144 } from '../../assets/svg/144.svg';
// import { ReactComponent as I145 } from '../../assets/svg/145.svg';
// import { ReactComponent as I146 } from '../../assets/svg/146.svg';
// import { ReactComponent as I147 } from '../../assets/svg/147.svg';
// import { ReactComponent as I148 } from '../../assets/svg/148.svg';
// import { ReactComponent as I149 } from '../../assets/svg/149.svg';
// import { ReactComponent as I150 } from '../../assets/svg/150.svg';

interface SvgProps {
    item: number;
    stroke: string;
    fill: string;
    rotate: number;
    scale: number;
}

function SvgItem({ item, stroke, fill, rotate, scale }: SvgProps) {
    let Component = I1;
    if (item === 1) Component = I1;
    if (item === 2) Component = I2;
    if (item === 3) Component = I3;
    if (item === 4) Component = I4;
    if (item === 5) Component = I5;
    if (item === 6) Component = I6;
    if (item === 7) Component = I7;
    if (item === 8) Component = I8;
    if (item === 9) Component = I9;
    if (item === 10) Component = I10;
    if (item === 11) Component = I11;
    if (item === 12) Component = I12;
    if (item === 13) Component = I13;
    if (item === 14) Component = I14;
    if (item === 15) Component = I15;
    if (item === 16) Component = I16;
    if (item === 17) Component = I17;
    if (item === 18) Component = I18;
    if (item === 19) Component = I19;
    if (item === 20) Component = I20;
    if (item === 21) Component = I21;
    if (item === 22) Component = I22;
    if (item === 23) Component = I23;
    if (item === 24) Component = I24;
    if (item === 25) Component = I25;
    if (item === 26) Component = I26;
    if (item === 27) Component = I27;
    if (item === 28) Component = I28;
    if (item === 29) Component = I29;
    if (item === 30) Component = I30;
    if (item === 31) Component = I31;
    if (item === 32) Component = I32;
    if (item === 33) Component = I33;
    if (item === 34) Component = I34;
    if (item === 35) Component = I35;
    if (item === 36) Component = I36;
    if (item === 37) Component = I37;
    if (item === 38) Component = I38;
    if (item === 39) Component = I39;
    if (item === 40) Component = I40;
    if (item === 41) Component = I41;
    if (item === 42) Component = I42;
    if (item === 43) Component = I43;
    if (item === 44) Component = I44;
    if (item === 45) Component = I45;
    if (item === 46) Component = I46;
    if (item === 47) Component = I47;
    if (item === 48) Component = I48;
    if (item === 49) Component = I49;
    if (item === 50) Component = I50;
    if (item === 51) Component = I51;
    if (item === 52) Component = I52;
    if (item === 53) Component = I53;
    if (item === 54) Component = I54;
    if (item === 55) Component = I55;
    if (item === 56) Component = I56;
    if (item === 57) Component = I57;
    if (item === 58) Component = I58;
    if (item === 59) Component = I59;
    if (item === 60) Component = I60;
    if (item === 61) Component = I61;
    if (item === 62) Component = I62;
    if (item === 63) Component = I63;
    if (item === 64) Component = I64;
    if (item === 65) Component = I65;
    if (item === 66) Component = I66;
    if (item === 67) Component = I67;
    if (item === 68) Component = I68;
    if (item === 69) Component = I69;
    if (item === 70) Component = I70;
    if (item === 71) Component = I71;
    if (item === 72) Component = I72;
    if (item === 73) Component = I73;
    if (item === 74) Component = I74;
    if (item === 75) Component = I75;
    if (item === 76) Component = I76;
    if (item === 77) Component = I77;
    if (item === 78) Component = I78;
    if (item === 79) Component = I79;
    if (item === 80) Component = I80;
    if (item === 81) Component = I81;
    if (item === 82) Component = I82;
    if (item === 83) Component = I83;
    if (item === 84) Component = I84;
    if (item === 85) Component = I85;
    if (item === 86) Component = I86;
    if (item === 87) Component = I87;
    if (item === 88) Component = I88;
    if (item === 89) Component = I89;
    if (item === 90) Component = I90;
    if (item === 91) Component = I91;
    if (item === 92) Component = I92;
    if (item === 93) Component = I93;
    if (item === 94) Component = I94;
    if (item === 95) Component = I95;
    if (item === 96) Component = I96;
    if (item === 97) Component = I97;
    if (item === 98) Component = I98;
    if (item === 99) Component = I99;
    if (item === 100) Component = I100;
    if (item === 101) Component = I101;
    if (item === 102) Component = I102;
    if (item === 103) Component = I103;
    if (item === 104) Component = I104;
    if (item === 105) Component = I105;
    if (item === 106) Component = I106;
    if (item === 107) Component = I107;
    if (item === 108) Component = I108;
    if (item === 109) Component = I109;
    if (item === 110) Component = I110;
    if (item === 111) Component = I111;
    if (item === 112) Component = I112;
    if (item === 113) Component = I113;
    if (item === 114) Component = I114;
    if (item === 115) Component = I115;
    if (item === 116) Component = I116;
    if (item === 117) Component = I117;
    if (item === 118) Component = I118;
    if (item === 119) Component = I119;
    if (item === 120) Component = I120;
    if (item === 121) Component = I121;
    if (item === 122) Component = I122;
    if (item === 123) Component = I123;
    if (item === 124) Component = I124;
    if (item === 125) Component = I125;
    if (item === 126) Component = I126;
    if (item === 127) Component = I127;
    if (item === 128) Component = I128;
    if (item === 129) Component = I129;
    if (item === 130) Component = I130;
    if (item === 131) Component = I131;
    if (item === 132) Component = I132;
    if (item === 133) Component = I133;
    if (item === 134) Component = I134;
    if (item === 135) Component = I135;
    // if (item === 136) Component = I136;
    // if (item === 137) Component = I137;
    // if (item === 138) Component = I138;
    // if (item === 139) Component = I139;
    // if (item === 140) Component = I140;
    // if (item === 141) Component = I141;
    // if (item === 142) Component = I142;
    // if (item === 143) Component = I143;
    // if (item === 144) Component = I144;
    // if (item === 145) Component = I145;
    // if (item === 146) Component = I146;
    // if (item === 147) Component = I147;
    // if (item === 148) Component = I148;
    // if (item === 149) Component = I149;
    // if (item === 150) Component = I150;


    
    let rotateX = 5
    let rotateY = 10
    let rotateZ = 0

    return (
        <Component
            stroke={stroke}
            fill={fill}
            style={{
                position: 'absolute',
                transform: `rotate(${rotate}deg) rotateX(${rotateX}deg) rotateY(${rotateY}deg) rotateZ(${rotateZ}deg) scale(${scale})`,
                // filter: `drop-shadow(0px 0px 0px rgb(0 0 0 / 1))`
            }}
        />
    );
}

export default SvgItem;
